### ISSUE TITLE
error https

### ISSUE THREAD

**Issue by antonellocaroli** [xdch47/moc#2]
Hi,

do you know what this error could be due to?

```
ERROR:
        moc not support https protocol
```
works with http links

`USE="aac alsa cache curl ffmpeg flac libsamplerate mad magic unicode vorbis wavpack -debug -jack -modplug -musepack -oss -pulseaudio (-sid) -sndfile -sndio -speex -timidity -tremor"`

**Comment by tomaszg7** [comment]
http://moc.daper.net/node/1815

**Comment by antonellocaroli** [comment]
thank you, but it was a problem on my system that had nothing to do with moc...now it works.
